platform :ios, '7.0'
target “Fade” do
pod 'FMDB'
pod 'CYLTabBarController'
pod "Qiniu"
pod 'AFNetworking'
pod 'Mantle'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJRefresh'
pod 'FMDB'
pod 'Masonry'
pod 'BlocksKit'

end

